BEGIN TRANSACTION;

BEGIN TRY
    INSERT INTO Customers VALUES (3,'Charlie');
    INSERT INTO Orders VALUES (104,3,500);

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;
    PRINT 'Transaction failed: ' + ERROR_MESSAGE();
END CATCH
